server {
    listen 443 ssl;

    ssl_certificate /certs/localhost+3.pem;
    ssl_certificate_key /certs/localhost+3-key.pem;

    location /api/ {
        proxy_pass http://pwa-backend:8080/api/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}